In [1]:
"""Numpy is a library for the Python programming language, adding support for large,
multi-dimensional arrays and matrices, along with a large collection
of high-level mathematical functions to operate on these arrays."""

import numpy as np

In [2]:
#row vector
vector_row = np.array([1,2,3])
#column vector ... see the number of square brackets carefully i did mistake here, Basically the array declaring 
#syntax for any type of vector is array([      ])
vector_column = np.array([[1],[2],[3]])

In [3]:
matrix = np.array([[1,2,3],[1,4,9]])
print(matrix)

[[1 2 3]
 [1 4 9]]


In [4]:
"""
Sparse Matrices store only non zero elements and assume all other values will be zero,
leading to significant computational savings.
sparsity = count zero elements / total elements
The matrix contained is sparse with many more zero values than data values.
The problem with representing these sparse matrices as dense matrices is that
memory is required and must be allocated for each 32-bit or even 64-bit zero value in the matrix
This is clearly a waste of memory as those zero values do not contain any information

"""
from scipy.sparse import csr_matrix
from numpy import count_nonzero
#Create a Matrix
matrix = np.array([[0,0],[0,1],[3,0]])
#Create Compressed Sparse Row(CSR) matrix, use csc if th matrix is of column type 
matrix_sparse = csr_matrix(matrix)
print(matrix_sparse)
sparsity = 1.0 - count_nonzero(matrix)/matrix.size
print(sparsity)
#(1,1) represents that the value of matrix at row 1 and column 1 is 1

  (1, 1)	1
  (2, 0)	3
0.6666666666666667


In [5]:
print(vector_row[:])

[1 2 3]


In [6]:
print(vector_row[:])

[1 2 3]


In [7]:
#selecting all the rows and second column of a matrix
print(matrix[:][1:2])

[[0 1]]


In [8]:
print(matrix.shape)

(3, 2)


In [9]:
print(matrix.size)

6


In [10]:
print(matrix.ndim)

2


In [11]:
# to apply  a function to multiple elements in array
add_100 = lambda i:i+100
vectorized_add_100 = np.vectorize(add_100)
print(vectorized_add_100(matrix))

[[100 100]
 [100 101]
 [103 100]]


In [12]:
print(np.max(matrix))

3


In [13]:
#prints the max element in each column
print(np.max(matrix,axis = 0))

[3 1]


In [14]:
#prints the maximum element in each row
print(np.max(matrix,axis = 1))

[0 1 3]


In [15]:
print(np.mean(matrix))

0.6666666666666666


In [16]:
print(np.std(matrix))

1.1055415967851334


In [17]:
print(np.var(matrix))

1.2222222222222225


In [21]:
print(matrix)
#see carefully how it got reshaped
print(matrix.reshape(2,3))

[[0 0]
 [0 1]
 [3 0]]
[[0 0 0]
 [1 3 0]]


In [23]:
print(matrix.flatten())

[0 0 0 1 3 0]


In [24]:
#Transpose of a matrix
print(matrix.T)

[[0 0 3]
 [0 1 0]]


In [35]:
newmatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
#determinant of matrix
print(np.linalg.det(newmatrix))

-9.51619735392994e-16


In [39]:
#rank of matrix
print(np.linalg.matrix_rank(newmatrix))

2


In [40]:
print(newmatrix.diagonal())

[1 5 9]


In [46]:
#printing dignol one aboev the main one
print(newmatrix.diagonal(offset = 1))

[2 6]


In [47]:
print(newmatrix.trace())

15


In [49]:
#getting evalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(newmatrix)

In [50]:
print(eigenvalues)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]


In [51]:
print(eigenvectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [52]:
#dot product
print(np.dot([1,2,3],[4,5,6]))
#similarly use np.add and np.subtract

32


In [55]:
#here not maching  as multiplication not possible
print(matrix*newmatrix)

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [57]:
print(np.linalg.inv(newmatrix))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [58]:
#generate the random numbers
np.random.seed(1)
#generate three random integers between 1 and 10
print(np.random.randint(0,11,3))

[5 8 9]


In [59]:
print(np.random.randint(0,11,3))

[5 0 0]


In [60]:
print(np.random.randint(0,11,3))


[1 7 6]


In [61]:
print(np.random.randint(0,11,3))

[9 2 4]


In [62]:
print(np.random.randint(0,11,3))

[5 2 4]


In [63]:
print(np.random.randint(0,11,3))

[10  2  4]


In [64]:
print(np.random.randint(0,11,3))


[7 7 9]


In [65]:
#Draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
print(np.random.normal(1.0,2.0,3))

[2.35446801 0.78624315 2.45054813]


In [66]:
print(np.random.randint(0,15,1))

[7]


In [67]:
print(np.random.randint(0,15,1))

[13]


In [68]:
print(np.random.randint(0,15,1))

[6]
